spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.dunkcode.cn:3306/pipeline_data_sys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password:
    hikari:
      max-lifetime: 50000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 600MB

logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog-dev.log

mybatis-plus:
  # configuration:
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#gq-image-store-path:
#图片访问URL的基准地址
project-host: localhost:8888/
mybatis-limit:
  pagesize: 20